/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#000412",
        "primary-container": "#0f1e36",
        "on-primary": "#ffffff",
        "on-primary-container": "#7886a3",
        "primary-fixed": "#d7e3ff",
        "primary-fixed-dim": "#b8c7e6",
        "on-primary-fixed": "#0c1b33",
        "on-primary-fixed-variant": "#394761",
        "secondary": "#006c53",
        "secondary-container": "#95f1d0",
        "secondary-fixed": "#98f4d3",
        "secondary-fixed-dim": "#7cd8b8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007057",
        "on-secondary-fixed": "#002117",
        "on-secondary-fixed-variant": "#00513e",
        "tertiary": "#000510",
        "tertiary-container": "#101f31",
        "on-tertiary-container": "#79879d",
        "surface": "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2df",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#44474d",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        "outline": "#75777e",
        "outline-variant": "#c5c6ce",
        "border-contrast": "#e2ddd5",
        "border-subtle": "#efece6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#faf9f6",
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "headline-xl": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-sm": ["'Hanken Grotesk'", "sans-serif"],
        "title-md": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "body-sm": ["'Hanken Grotesk'", "sans-serif"],
        "label-lg": ["'Hanken Grotesk'", "sans-serif"],
        "label-md": ["'Hanken Grotesk'", "sans-serif"],
        "label-sm": ["'Hanken Grotesk'", "sans-serif"],
        "metric-display": ["'Hanken Grotesk'", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "metric-display": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "margin": "2.5rem",
      }
    },
  },
  plugins: [],
}
